import { ButtonColorProps, CoreStaticStylesType } from "../../types/coreTypes";

const ButtonCSSUtil: CoreStaticStylesType = {
    /*
        CUSTOM CLASSES FOR ELEMENTS
    */
    graceController: ({ extractGaladrielClasses }) => {
        const genButton = ({
            bgColor,
            borderColor,
            bsColorOne,
            bsColorTwo,
            filterColor,
            textColor,
        }: ButtonColorProps) => ({
            background: bgColor,
            border: `1px solid ${borderColor}`,
            "border-radius": "10px",
            "box-shadow": `inset -4px 4px 9px ${bsColorOne}, inset 4px -4px 9px ${bsColorTwo}`,
            display: "inline-block",
            "font-size": "16px",
            "font-weight": "bold",
            "text-align": "center",
            "text-decoration": "none",
            padding: "15px 30px",
            margin: "15px",
            "user-select": "none",
            height: "auto",
            width: "auto",
            cursor: "pointer",
            color: textColor,
            transition: "transform 0.3s",
            position: "relative",
            "z-index": "1",
            filter: `drop-shadow(6px 4px 4px ${filterColor})`,
            "&:hover": "{ transform: scale(1.05); opacity: 0.8; }",
            "&:focus": `{ outline: none; box-shadow: 0 0 5px ${bsColorOne}, 0 0 5px ${bsColorTwo}; }`,
            "&:active": "{ transform: scale(0.95); transition: transform 0.1s; }",
            "&:disabled": "{ background: #708090; color: #b8b8b8; cursor: default; box-shadow: inset -4px 4px 9px #5f6d7a, inset 4px -4px 9px #8193a6; }",
            "&:disabled:hover": "{ transform: scale(1); opacity:1; }"
        });

        return extractGaladrielClasses({
            ".$element-button-light-gray": genButton({
                bgColor: "#e0e0e0",
                borderColor: "#708090",
                bsColorOne: "#b8b8b8",
                bsColorTwo: "#FFFFF0",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-light-gold": genButton({
                bgColor: "#FFD700",
                borderColor: "#708090",
                bsColorOne: "#debb00",
                bsColorTwo: "#fff300",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-gold": genButton({
                bgColor: "#FFA500",
                borderColor: "#708090",
                bsColorOne: "#de9000",
                bsColorTwo: "#ffba00",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-dark-gold": genButton({
                bgColor: "#B8860B",
                borderColor: "#708090",
                bsColorOne: "#a0750a",
                bsColorTwo: "#d0970c",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-old-gold": genButton({
                bgColor: "#CFB53B",
                borderColor: "#708090",
                bsColorOne: "#b49d33",
                bsColorTwo: "#eacd43",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-light-blue": genButton({
                bgColor: "#B3E5FC",
                borderColor: "#708090",
                bsColorOne: "#93bccf",
                bsColorTwo: "#d3ffff",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-sky-blue": genButton({
                bgColor: "#80D8FF",
                borderColor: "#708090",
                bsColorOne: "#6db8d9",
                bsColorTwo: "#93f8ff",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-turquoise-blue": genButton({
                bgColor: "#00BFFF",
                borderColor: "#708090",
                bsColorOne: "#00a2d9",
                bsColorTwo: "#00dcff",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-pink": genButton({
                bgColor: "#FF69B4",
                borderColor: "#708090",
                bsColorOne: "#d15694",
                bsColorTwo: "#ff7cd4",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-dark-coral-pink": genButton({
                bgColor: "#FF4040",
                borderColor: "#708090",
                bsColorOne: "#d13434",
                bsColorTwo: "#ff4c4c",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-light-olive-green": genButton({
                bgColor: "#BCE954",
                borderColor: "#708090",
                bsColorOne: "#9abf45",
                bsColorTwo: "#deff63",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-olive-green": genButton({
                bgColor: "#808000",
                borderColor: "#708090",
                bsColorOne: "#696900",
                bsColorTwo: "#979700",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-dark-olive-green": genButton({
                bgColor: "#556B2F",
                borderColor: "#708090",
                bsColorOne: "#465827",
                bsColorTwo: "#647e37",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-deep-olive-green": genButton({
                bgColor: "#3B5323",
                borderColor: "#708090",
                bsColorOne: "#30441d",
                bsColorTwo: "#466229",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-deep-indigo": genButton({
                bgColor: "#1F497D",
                borderColor: "#708090",
                bsColorOne: "#193c67",
                bsColorTwo: "#255694",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-indigo": genButton({
                bgColor: "#4B0082",
                borderColor: "#708090",
                bsColorOne: "#3e006b",
                bsColorTwo: "#590099",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-light-indigo": genButton({
                bgColor: "#5D8AA8",
                borderColor: "#708090",
                bsColorOne: "#4c718a",
                bsColorTwo: "#6ea3c6",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-silver": genButton({
                bgColor: "#A9A9A9",
                borderColor: "#708090",
                bsColorOne: "#8b8b8b",
                bsColorTwo: "#c7c7c7",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-deep-teal": genButton({
                bgColor: "#003333",
                borderColor: "#708090",
                bsColorOne: "#002a2a",
                bsColorTwo: "#003c3c",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-deep-ruby": genButton({
                bgColor: "#7A0008",
                borderColor: "#708090",
                bsColorOne: "#640007",
                bsColorTwo: "#900009",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-dark-ruby": genButton({
                bgColor: "#9F000F",
                borderColor: "#708090",
                bsColorOne: "#82000c",
                bsColorTwo: "#bc0012",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-ruby": genButton({
                bgColor: "#E41B17",
                borderColor: "#708090",
                bsColorOne: "#bb1613",
                bsColorTwo: "#ff201b",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-light-ruby": genButton({
                bgColor: "#F62217",
                borderColor: "#708090",
                bsColorOne: "#ca1c13",
                bsColorTwo: "#ff281b",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-light-orchid": genButton({
                bgColor: "#E6A8D7",
                borderColor: "#708090",
                bsColorOne: "#bd8ab0",
                bsColorTwo: "#ffc6fe",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-orchid": genButton({
                bgColor: "#DA70D6",
                borderColor: "#708090",
                bsColorOne: "#b35caf",
                bsColorTwo: "#ff84fd",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-dark-orchid": genButton({
                bgColor: "#9932CC",
                borderColor: "#708090",
                bsColorOne: "#7d29a7",
                bsColorTwo: "#b53bf1",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-deep-orchid": genButton({
                bgColor: "#8B4789",
                borderColor: "#708090",
                bsColorOne: "#723a70",
                bsColorTwo: "#a454a2",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#FFFFF0",
            }),
            ".$element-button-electric-blue": genButton({
                bgColor: "#3498db",
                borderColor: "#708090",
                bsColorOne: "#2c81ba",
                bsColorTwo: "#3caffc",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-emerald-green": genButton({
                bgColor: "#2ecc71",
                borderColor: "#708090",
                bsColorOne: "#27ad60",
                bsColorTwo: "#35eb82",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-bright-green": genButton({
                bgColor: "#27ae60",
                borderColor: "#708090",
                bsColorOne: "#219452",
                bsColorTwo: "#2dc86e",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-vivid-orange": genButton({
                bgColor: "#e67e22",
                borderColor: "#708090",
                bsColorOne: "#c46b1d",
                bsColorTwo: "#ff9127",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
            ".$element-button-bold-red": genButton({
                bgColor: "#e74c3c",
                borderColor: "#708090",
                bsColorOne: "#c44133",
                bsColorTwo: "#ff5745",
                filterColor: "rgba(112, 128, 144, 0.7)",
                textColor: "#333333",
            }),
        });
    },
    backgroundColor: ({ extractGaladrielClasses }) =>
        extractGaladrielClasses({
            ".$background-blue": {
                "background-color": "blue",
                "border-radius": "10px",
                border: "1px solid #fff555",
                height: "100vh",
            },
            ".$background-black": {
                "background-color": "black",
                "border-radius": "10px",
                border: "1px solid #FFFFF0",
                height: "100vh",
                padding: 0,
                margin: 0,
            },
            ".$background-turquoise-blue": {
                "background-color": "#00FFF0",
                "border-radius": "10px",
                border: "1px solid black",
                height: "100vh",
                padding: 0,
                margin: 0,
            },
        }),
};

export { ButtonCSSUtil };
